# Generated by Django 5.2.7 on 2025-10-17 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('cashout_time', models.DateTimeField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.codes')),
            ],
        ),
        migrations.CreateModel(
            name='UsedCodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.codes')),
            ],
        ),
    ]
