# Generated by Django 5.2.9 on 2025-12-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_history_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
