# Generated by Django 5.2.9 on 2025-12-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_codes_value_alter_history_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usedcodes',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
