# Generated by Django 5.2.9 on 2026-01-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_codes_id_alter_history_id_alter_usedcodes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
