# Generated by Django 5.2.7 on 2025-12-29 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('BETTING', 'Betting Phase'), ('SPINNING', 'Spinning Phase'), ('COMPLETED', 'Completed')], default='BETTING', max_length=10)),
                ('winning_color', models.CharField(blank=True, choices=[('GRAY', 'Gray'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GOLD', 'Gold')], max_length=4, null=True)),
                ('winning_slot', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spin_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('GRAY', 'Gray'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GOLD', 'Gold')], max_length=4)),
                ('amount', models.FloatField()),
                ('payout', models.FloatField(default=0)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_bets', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='roulette.gameround')),
            ],
            options={
                'ordering': ['-placed_at'],
                'unique_together': {('user', 'round', 'color')},
            },
        ),
    ]
