# Generated by Django 5.2.9 on 2026-01-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bet',
            name='payout',
            field=models.BigIntegerField(default=0),
        ),
    ]
