# Generated by Django 5.2.7 on 2025-10-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('balance', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('cashout_time', models.DateTimeField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.codes')),
            ],
        ),
        migrations.CreateModel(
            name='UsedCodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.codes')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
